pub mod initialize_competition;
pub mod register_player;
pub mod update_player_stats;
pub mod register_agent;
pub mod agent_staking;
pub mod squad;
pub mod tournament;
pub mod promote_relegate;
pub mod anti_gaming;

pub use initialize_competition::*;
pub use register_player::*;
pub use update_player_stats::*;
pub use register_agent::*;
pub use agent_staking::*;
pub use squad::*;
pub use tournament::*;
pub use promote_relegate::*;
pub use anti_gaming::*;
